openapi: 3.0.0
info:
  title: The Joy Digi API
  version: 1.0.0
  description: API documentation for The Joy Digi Next.js application.
servers:
  - url: /api
paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    example: Hello from Next.js API!
  /contact:
    post:
      summary: Submits a contact form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Contact form submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your message has been sent.
  /booking:
    post:
      summary: Submits a booking request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                service:
                  type: string
      responses:
        '200':
          description: Booking request submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Your booking request has been received.
  /gallery-photos:
    get:
      summary: Returns a list of gallery photos
      responses:
        '200':
          description: A list of gallery photos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    url:
                      type: string
                    alt:
                      type: string
  /hero-images:
    get:
      summary: Returns a list of hero images
      responses:
        '200':
          description: A list of hero images
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    url:
                      type: string
                    alt:
                      type: string
  /interests:
    get:
      summary: Returns a list of interests
      responses:
        '200':
          description: A list of interests
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Adds a new interest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Interest added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Interest added.
  /tiktok/auth:
    get:
      summary: Initiates TikTok authentication
      responses:
        '200':
          description: Redirects to TikTok authentication page
  /tiktok/callback:
    get:
      summary: Handles TikTok authentication callback
      responses:
        '200':
          description: TikTok authentication successful
  /tiktok/videos:
    get:
      summary: Returns a list of TikTok videos
      responses:
        '200':
          description: A list of TikTok videos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    url:
                      type: string
                    description:
                      type: string
