openapi: 3.1.0
info:
  title: The Joy Digi API
  version: 1.0.0
  description: API documentation for The Joy Digi Next.js application.
servers:
  - url: /api
paths:
  /interests:
    get:
      summary: Returns a list of interests
      responses:
        '200':
          description: A list of interests
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Adds a new interest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Interest added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Interest added.